### DISCUSSION TITLE
Unopim behind traefik

### DISCUSSION THREAD

**Discussion by cristianku** [unopim/unopim#121] [General]
Has anyone tried to put unopim behind traefik .

I am getting not correctly loaded the login and the login doesnt work

<img width="396" alt="Screenshot 2025-03-21 at 21 38 26" src="https://github.com/user-attachments/assets/e2e809b6-5f18-483c-9bf5-bddb61ae3baf" />

This is my Traefik configuration:

```
http:
  routers:
    unopim-rtr:
      rule: "Host(`unopim.mydomain.com`)"

      entryPoints:
        - https
      service: unopim-svc
      priority: 1000

      tls:
        certResolver: cloudflare

  services:
    unopim-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://internal-ip:8000"
```
